"""create main tables

Revision ID: 4dc6e454f9b7
Revises: 
Create Date: 2024-07-14 19:10:24.654964

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4dc6e454f9b7"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("uuid", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "houses",
        sa.Column("uuid", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("owner_uuid", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_uuid"],
            ["users.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "rooms",
        sa.Column("uuid", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("house_uuid", sa.String(), nullable=True),
        sa.Column("capacity", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["house_uuid"],
            ["houses.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "residents",
        sa.Column("uuid", sa.String(), nullable=False),
        sa.Column("user_uuid", sa.String(), nullable=True),
        sa.Column("room_uuid", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["room_uuid"],
            ["rooms.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["user_uuid"],
            ["users.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("residents")
    op.drop_table("rooms")
    op.drop_table("houses")
    op.drop_table("users")
    # ### end Alembic commands ###
