"""initial migration

Revision ID: 66ec7ae2eb74
Revises: 
Create Date: 2024-08-04 16:19:14.526530

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "66ec7ae2eb74"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("uuid", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "houses",
        sa.Column("uuid", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("owner_uuid", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_uuid"],
            ["users.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "residents",
        sa.Column("uuid", sa.String(), nullable=False),
        sa.Column("user_uuid", sa.String(), nullable=True),
        sa.Column("house_uuid", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["house_uuid"],
            ["houses.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["user_uuid"],
            ["users.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("residents")
    op.drop_table("houses")
    op.drop_table("users")
    # ### end Alembic commands ###
